
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 134
#define YY_END_OF_BUFFER 135
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[480] =
    {   0,
        0,    0,  135,  133,  132,  132,   81,  133,  101,   98,
      133,  122,  123,   96,   94,  126,   95,  125,   97,   72,
       72,   84,  129,  117,   80,  116,   83,  119,   69,   69,
      120,  121,  100,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,  127,   99,  128,   82,   89,    0,
      131,    0,  112,   90,  109,    0,    0,  107,   92,    0,
       72,   72,  105,   93,  106,   85,    0,   72,    0,   70,
      108,    0,   72,    0,   75,    0,   75,    0,   75,   75,
      118,  102,   88,   86,   87,  103,   69,   69,  111,   69,

       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   30,   69,   69,   69,   69,
       69,   69,   69,   69,   26,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   13,   69,   69,   69,
       69,   69,   69,   69,  110,   91,  131,    0,   78,   78,
      124,    0,    0,    0,    0,   70,   70,   72,    0,    0,
       77,    0,   75,    0,   73,  113,  114,  104,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   21,

       69,   69,   69,   51,   69,   69,   69,   22,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       53,   69,   10,   69,   69,   69,   69,   69,    0,    0,
        0,    0,    0,   71,    0,   70,    0,   74,   77,    0,
       73,   73,   73,   73,    0,   73,  115,   69,   69,   69,
       69,   69,   39,   44,   69,   54,   69,   69,   69,   69,
       69,   40,   45,   69,   69,   69,   69,   69,   31,   69,
       69,   69,   69,   61,   69,   69,    0,    2,   15,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,

       69,   69,   69,   69,   69,   33,   69,   69,    1,    6,
       58,   69,   69,   14,   69,    0,    0,    0,   71,    0,
       77,   73,   73,   73,   73,    0,   73,   73,   73,   73,
       73,   76,   69,   69,   69,   69,   34,   49,   59,   64,
       69,   69,   69,   69,   69,   55,   65,   69,   69,   69,
       69,   69,   69,    0,    4,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   52,   69,   69,   67,   69,
       69,   38,   69,   69,   68,   18,   79,   73,   73,   73,
       73,   73,   76,   76,   76,   69,   69,   24,   69,   69,
       69,   35,   69,   69,   69,   69,   41,   69,   69,    7,

       66,    0,   69,   69,   69,   69,   69,   42,   16,   69,
       47,    9,   57,   69,   23,   69,   43,   69,   69,   69,
       69,   29,   69,   25,    3,   50,   60,   69,   69,   69,
        0,   27,    8,   32,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   19,   20,   69,   69,   69,    0,   69,
       12,    5,   62,   69,   69,   69,   63,   69,   69,   69,
       56,    0,   37,   69,   48,   69,   69,   36,   46,   11,
       69,   17,   69,   69,   69,   28,   69,   69,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   31,   33,   34,   35,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   37,
       36,   38,   36,   36,   36,   36,   36,   39,   36,   36,
       40,   41,   42,   43,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   36,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
       68,   69,   70,   71,   72,   73,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[74] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    1,    3,    4,    1,    5,
        5,    5,    5,    1,    1,    1,    1,    1,    1,    1,
        5,    5,    5,    5,    5,    6,    6,    6,    6,    1,
        1,    1,    1,    5,    5,    5,    5,    5,    5,    5,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    1,
        1,    1,    1
    } ;

static const flex_int16_t yy_base[491] =
    {   0,
        0,    0,  778,  779,  779,  779,  750,   66,  749,   65,
      764,  779,  779,  747,   61,  779,   73,   88,   85,  115,
      165,  749,  779,   51,  745,   58,  779,  779,    0,  718,
      779,  779,  743,  198,   41,   55,   69,   31,   63,   86,
      711,   69,  710,  709,  108,  707,  106,  716,  126,   82,
      702,   57,   45,  710,  779,  102,  779,  779,  779,  138,
      754,  758,  779,  779,  779,  749,  748,  779,  779,  181,
        0,    0,  779,  779,  779,  779,  740,  229,  155,  738,
      779,  185,  178,  216,  779,  265,  779,  738,  779,  779,
      779,  728,  779,  779,  779,  149,    0,  700,  779,    0,

        0,  274,    0,    0,    0,  691,  690,  693,  701,  686,
      118,  703,  702,  689,  695,  680,  681,  678,   93,  686,
      683,  681,  677,  674,    0,  677,  133,  678,  686,  670,
      666,  674,  675,  680,  681,  666,  170,  680,  175,  680,
      666,  123,  664,  669,  664,  200,    0,  236,  671,  658,
      138,  665,  654,  667,  779,  779,  779,  189,  704,  703,
      779,  251,  252,  287,  269,    0,  694,  299,  293,  223,
      306,  308,  336,    0,  328,  779,  779,  685,  662,  370,
      647,  660,  653,  662,  657,  656,  657,  642,  640,  177,
      656,  654,  650,  642,  639,  647,  633,  649,  648,    0,

      634,   87,  628,  641,  638,  624,  634,    0,  669,  630,
      627,  629,  626,  616,  205,  625,  621,  614,  613,  621,
      614,  611,  620,  623,  608,  623,  607,  610,  610,  617,
        0,  603,    0,  616,  618,  607,  609,  605,  218,  651,
      655,  339,  361,  779,  391,  638,  380,  395,  377,  392,
      398,    0,  455,    0,  254,    0,  779,  594,  594,  593,
      604,  598,    0,    0,  599,    0,  588,  586,  595,  583,
      591,    0,    0,  584,  587,  594,  587,  578,    0,  591,
      578,  593,  576,    0,  581,  570,  572,    0,  571,  586,
      552,  546,  533,  528,  527,  518,  525,  516,  527,  512,

      521,  526,  511,  523,  517,    0,  502,  505,    0,    0,
        0,  503,  516,    0,  516,  555,  365,  369,  420,  255,
      291,    0,  512,    0,    0,  288,  308,  321,    0,  324,
      391,  405,  503,  509,  490,  507,    0,    0,    0,    0,
      494,  495,  499,  479,  493,  485,    0,  483,  475,  480,
      486,  482,  481,  479,    0,  474,  461,  460,  475,  473,
      473,  471,  457,  460,  468,    0,  468,  450,    0,  460,
      450,  448,  456,  455,    0,    0,  779,  412,  427,    0,
      433,  434,    0,    0,    0,  463,  459,    0,  441,  433,
      433,    0,  433,  432,  425,  442,    0,  438,  439,    0,

        0,  438,  433,  419,  431,  416,  425,    0,    0,  422,
        0,    0,    0,  418,    0,  409,    0,  235,  411,  427,
      401,    0,  414,    0,    0,    0,    0,  405,  412,  413,
      404,    0,    0,    0,  409,  394,  393,  395,  395,  384,
      384,  346,  336,    0,    0,  322,  324,  332,  329,  325,
        0,    0,    0,  314,  297,  289,    0,  289,  283,  267,
        0,  259,    0,  233,    0,  244,  206,    0,    0,  779,
      192,    0,  166,  123,  116,    0,   76,    0,  779,  583,
      589,  591,  597,  603,  606,  611,  617,  117,  623,  627
    } ;

static const flex_int16_t yy_def[491] =
    {   0,
      479,    1,  479,  479,  479,  479,  479,  480,  479,  479,
      481,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  482,  482,
      479,  479,  479,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  479,  479,  479,  479,  479,  480,
      479,  480,  479,  479,  479,  481,  481,  479,  479,  479,
       20,   21,  479,  479,  479,  479,  479,  479,  483,  484,
      479,  479,   20,  479,  479,  479,  479,  485,  479,  479,
      479,  479,  479,  479,  479,  479,  482,  482,  479,   34,

      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  479,  479,  479,  486,  481,  481,
      479,  483,  483,  487,  483,  484,  484,  479,  479,  479,
      479,  479,  479,  488,  485,  479,  479,  479,  482,   34,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,

      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  486,  479,
      486,  483,  483,  479,  489,  484,  479,  479,  479,  479,
      488,  175,  479,  175,  490,  175,  479,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  479,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,

      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  479,  483,  483,  483,  479,
      479,  251,  479,  251,  251,  490,  253,  253,  253,  253,
      253,  490,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  479,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  479,  323,  323,  323,
      323,  323,  332,  332,  332,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,

      482,  479,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      479,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  479,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  479,  482,  482,  482,  482,  482,  482,  482,  479,
      482,  482,  482,  482,  482,  482,  482,  482,    0,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479
    } ;

static const flex_int16_t yy_nxt[853] =
    {   0,
        4,    5,    6,    5,    4,    5,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   21,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   29,   29,   29,   29,   29,   29,   30,   29,   31,
        4,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   29,   42,   29,   43,   44,   45,   46,   47,   29,
       48,   49,   50,   51,   52,   53,   29,   54,   29,   55,
       56,   57,   58,   61,   64,   69,   92,   93,   70,  115,
       71,   72,   72,   72,   95,   96,  106,   73,  116,   74,
       70,   65,   71,   72,   72,   72,  152,  153,   79,   75,

       76,  150,  107,   80,   72,   77,   62,   78,   78,   78,
       78,   81,  108,  111,  151,  109,   72,  117,  125,  118,
      112,  251,  110,  113,  126,  127,  114,  478,  155,  119,
      120,   78,   82,  146,   83,   83,   83,   72,  121,  147,
      122,  280,  148,  123,  281,  157,   84,   85,   86,   87,
      135,  195,  130,   88,  136,  196,  131,  163,   83,  163,
       84,  477,   89,   86,   90,  132,  137,  222,  164,  138,
      476,  133,  156,  165,  140,  177,  178,  141,   62,  186,
      187,   88,   70,  223,   72,   72,   72,   72,  142,  143,
      234,  144,  235,  145,  203,  204,  240,   85,   86,   87,

       78,   78,   78,   78,  168,  168,  168,   78,   72,  479,
      475,  169,   89,   86,   90,   70,  479,  100,  100,  100,
      100,  217,  214,  479,   78,  240,  169,  215,  168,  241,
      101,  102,  103,  170,  218,  171,  171,  219,  268,  269,
      474,  100,  249,  249,  479,  104,  102,  105,   78,   78,
       78,   78,  227,  163,  163,  163,  163,  473,  241,  171,
      228,   85,   86,   87,  164,  164,  249,  293,  326,  294,
      326,  163,   78,  163,  321,  321,   89,   86,   90,  172,
      229,  172,  245,  440,  173,  173,  173,  173,  172,  243,
      172,  243,  472,  180,  180,  180,  180,  441,  321,  230,

      164,  471,  479,  231,  479,  244,  470,  247,  173,  247,
      321,  321,  248,  248,  248,  173,  469,  180,  168,  168,
      168,   78,  479,  170,  479,  171,  171,  173,  173,  173,
      173,   85,  169,   87,  321,  479,  248,  479,  479,  250,
      479,  163,  168,  163,  468,  174,   89,  169,   90,  171,
      467,  173,  164,  466,  250,  173,  173,  173,  173,  465,
      252,  253,  254,  163,  255,  163,  464,  163,   85,  163,
       87,  163,  463,  163,  164,  256,  253,  462,  164,  173,
      461,  460,  164,   89,  459,   90,  255,  479,  458,  180,
      180,  180,  180,  318,  457,  318,  249,  249,  255,  248,

      248,  248,  173,   97,  164,  479,  320,  479,  320,  319,
      250,  321,  321,  180,  248,  248,  248,  173,   97,  479,
      249,  479,  163,  248,  163,  250,  479,   85,  479,   87,
      322,  323,  324,  245,  255,  321,  456,  383,  248,  384,
      455,  479,   89,  479,   90,  325,  323,  479,  479,  479,
      479,  454,  385,  453,  452,  451,  255,  450,  449,  448,
      447,  446,  445,  444,  443,  442,  439,  438,  255,  326,
      437,  326,  174,  436,  327,  327,  327,  327,  435,  434,
      433,  432,  431,  430,  429,  327,  327,  328,  329,  330,
      428,  255,  427,  426,  425,  424,  423,  422,  327,  327,

      327,  327,  331,  329,  327,  421,  420,  419,  418,  417,
      416,  415,  414,  255,  413,  412,  411,  410,  409,  408,
      407,  406,  405,  404,  403,  255,  326,  402,  326,  401,
      400,  378,  378,  378,  378,  399,  398,  397,  396,  395,
      394,  393,  378,  378,  379,  380,  381,  392,  255,  391,
      390,  389,  388,  387,  386,  378,  378,  378,  378,  382,
      380,  378,  377,  376,  375,  374,  373,  372,  371,  370,
      255,  369,  368,  367,  366,  365,  364,  363,  362,  361,
      360,  359,  255,   60,   60,   60,   60,   60,   60,   66,
      358,   66,   66,   66,   66,   97,   97,  162,  162,  162,

      162,  162,  162,  166,  357,  166,  166,  166,  166,  175,
      175,  239,  239,  239,  239,  239,  239,  242,  242,  242,
      242,  242,  242,  317,  317,  317,  317,  317,  317,  332,
      356,  332,  355,  354,  353,  352,  351,  350,  349,  348,
      347,  346,  309,  345,  344,  343,  342,  341,  340,  339,
      338,  337,  336,  335,  334,  333,  167,  479,  316,  315,
      314,  313,  312,  311,  310,  309,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  279,  278,  277,  276,  275,  274,  273,  272,  271,

      270,  267,  266,  265,  264,  263,  262,  261,  260,  259,
      258,  257,  246,  160,  159,  238,  237,  236,  233,  232,
      226,  225,  224,  221,  220,  216,  213,  212,  211,  210,
      209,  208,  207,  206,  205,  202,  201,  200,  199,  198,
      197,  194,  193,  192,  191,  190,  189,  188,  185,  184,
      183,  182,  181,  179,  176,  174,  167,  161,  160,  159,
      479,  158,  154,  149,  139,  134,  129,  128,  124,   99,
       98,   94,   91,   68,   67,   63,   59,  479,    3,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,

      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479
    } ;

static const flex_int16_t yy_chk[853] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    8,   10,   15,   24,   24,   15,   38,
       15,   15,   15,   15,   26,   26,   35,   15,   38,   17,
       17,   10,   17,   17,   17,   17,   53,   53,   19,   17,

       17,   52,   35,   19,   15,   18,    8,   18,   18,   18,
       18,   19,   36,   37,   52,   36,   17,   39,   42,   39,
       37,  488,   36,   37,   42,   42,   37,  477,   56,   39,
       40,   18,   20,   50,   20,   20,   20,   20,   40,   50,
       40,  202,   50,   40,  202,   60,   20,   20,   20,   20,
       47,  119,   45,   20,   47,  119,   45,   79,   20,   79,
       20,  475,   20,   20,   20,   45,   47,  142,   79,   47,
      474,   45,   56,   79,   49,   96,   96,   49,   60,  111,
      111,   20,   21,  142,   21,   21,   21,   21,   49,   49,
      151,   49,  151,   49,  127,  127,  158,   21,   21,   21,

       70,   70,   70,   70,   82,   82,   82,   82,   21,   83,
      473,   83,   21,   21,   21,   34,   83,   34,   34,   34,
       34,  139,  137,   83,   70,  239,   83,  137,   82,  158,
       34,   34,   34,   84,  139,   84,   84,  139,  190,  190,
      471,   34,  170,  170,   83,   34,   34,   34,   78,   78,
       78,   78,  146,  162,  163,  162,  163,  467,  239,   84,
      146,   78,   78,   78,  162,  163,  170,  215,  255,  215,
      255,  165,   78,  165,  320,  320,   78,   78,   78,   86,
      148,   86,  165,  418,   86,   86,   86,   86,  102,  164,
      102,  164,  466,  102,  102,  102,  102,  418,  320,  148,

      164,  464,  326,  148,  326,  164,  462,  169,   86,  169,
      321,  321,  169,  169,  169,  169,  460,  102,  168,  168,
      168,  168,  327,  171,  327,  171,  171,  172,  172,  172,
      172,  168,  168,  168,  321,  328,  169,  328,  330,  171,
      330,  242,  168,  242,  459,  175,  168,  168,  168,  171,
      458,  172,  242,  456,  171,  173,  173,  173,  173,  455,
      175,  175,  175,  243,  175,  243,  454,  317,  173,  317,
      173,  318,  450,  318,  243,  175,  175,  449,  317,  173,
      448,  447,  318,  173,  446,  173,  175,  180,  443,  180,
      180,  180,  180,  245,  442,  245,  249,  249,  175,  247,

      247,  247,  247,  180,  245,  331,  250,  331,  250,  245,
      249,  250,  250,  180,  248,  248,  248,  248,  180,  332,
      249,  332,  319,  247,  319,  249,  378,  248,  378,  248,
      251,  251,  251,  319,  251,  250,  441,  332,  248,  332,
      440,  379,  248,  379,  248,  251,  251,  381,  382,  381,
      382,  439,  332,  438,  437,  436,  251,  435,  431,  430,
      429,  428,  423,  421,  420,  419,  416,  414,  251,  253,
      410,  253,  253,  407,  253,  253,  253,  253,  406,  405,
      404,  403,  402,  399,  398,  253,  253,  253,  253,  253,
      396,  253,  395,  394,  393,  391,  390,  389,  253,  253,

      253,  253,  253,  253,  253,  387,  386,  374,  373,  372,
      371,  370,  368,  253,  367,  365,  364,  363,  362,  361,
      360,  359,  358,  357,  356,  253,  323,  354,  323,  353,
      352,  323,  323,  323,  323,  351,  350,  349,  348,  346,
      345,  344,  323,  323,  323,  323,  323,  343,  323,  342,
      341,  336,  335,  334,  333,  323,  323,  323,  323,  323,
      323,  323,  316,  315,  313,  312,  308,  307,  305,  304,
      323,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      294,  293,  323,  480,  480,  480,  480,  480,  480,  481,
      292,  481,  481,  481,  481,  482,  482,  483,  483,  483,

      483,  483,  483,  484,  291,  484,  484,  484,  484,  485,
      485,  486,  486,  486,  486,  486,  486,  487,  487,  487,
      487,  487,  487,  489,  489,  489,  489,  489,  489,  490,
      290,  490,  289,  287,  286,  285,  283,  282,  281,  280,
      278,  277,  276,  275,  274,  271,  270,  269,  268,  267,
      265,  262,  261,  260,  259,  258,  246,  241,  240,  238,
      237,  236,  235,  234,  232,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      214,  213,  212,  211,  210,  209,  207,  206,  205,  204,
      203,  201,  199,  198,  197,  196,  195,  194,  193,  192,

      191,  189,  188,  187,  186,  185,  184,  183,  182,  181,
      179,  178,  167,  160,  159,  154,  153,  152,  150,  149,
      145,  144,  143,  141,  140,  138,  136,  135,  134,  133,
      132,  131,  130,  129,  128,  126,  124,  123,  122,  121,
      120,  118,  117,  116,  115,  114,  113,  112,  110,  109,
      108,  107,  106,   98,   92,   88,   80,   77,   67,   66,
       62,   61,   54,   51,   48,   46,   44,   43,   41,   33,
       30,   25,   22,   14,   11,    9,    7,    3,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,

      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479,  479,  479,  479,  479,  479,  479,  479,  479,
      479,  479
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tokenizer.l"
#line 2 "tokenizer.l"
    #include<stdio.h>
    #include"string.h"
    #include "parser.tab.h"
#line 792 "lex.yy.c"
#line 793 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 7 "tokenizer.l"

#line 1012 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 480 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 779 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 8 "tokenizer.l"
{sscanf(yytext,"%s", yylval.data);
            return (BooleanLiteral);
            }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 11 "tokenizer.l"
{sscanf(yytext,"%s", yylval.data);
            return (NullLiteral);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 13 "tokenizer.l"
{return(Exports);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 14 "tokenizer.l"
{return(Opens);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 15 "tokenizer.l"
{return(Requires);} 
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 16 "tokenizer.l"
{return(Uses);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 17 "tokenizer.l"
{return(Module);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 18 "tokenizer.l"
{return(Permits);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 19 "tokenizer.l"
{return(Sealed);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 20 "tokenizer.l"
{return(Var);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 21 "tokenizer.l"
{return(Non_sealed);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 22 "tokenizer.l"
{return(Provides);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 23 "tokenizer.l"
{return(To);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 24 "tokenizer.l"
{return(With);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 25 "tokenizer.l"
{return(Open);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 26 "tokenizer.l"
{return(Record);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 27 "tokenizer.l"
{return(Transitive);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 28 "tokenizer.l"
{return(Yield);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 29 "tokenizer.l"
{return(Abstract);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 30 "tokenizer.l"
{return(Continue);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 31 "tokenizer.l"
{return(For);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 32 "tokenizer.l"
{return(New);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 33 "tokenizer.l"
{return(Switch);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 34 "tokenizer.l"
{return(Assert);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 35 "tokenizer.l"
{return(Default);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 36 "tokenizer.l"
{return(If);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 37 "tokenizer.l"
{return(Package);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 38 "tokenizer.l"
{return(Synchronized);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 39 "tokenizer.l"
{return(Boolean);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 40 "tokenizer.l"
{return(Do);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 41 "tokenizer.l"
{return(Goto);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 42 "tokenizer.l"
{return(Private);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 43 "tokenizer.l"
{return(This);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 44 "tokenizer.l"
{return(Break);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 45 "tokenizer.l"
{return(Double);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 46 "tokenizer.l"
{return(Implements);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 47 "tokenizer.l"
{return(Protected);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 48 "tokenizer.l"
{return(Throw);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 49 "tokenizer.l"
{return(Byte);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 50 "tokenizer.l"
{return(Else);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 51 "tokenizer.l"
{return(Import);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 52 "tokenizer.l"
{return(Public);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 53 "tokenizer.l"
{return(Throws);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 54 "tokenizer.l"
{return(Case);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 55 "tokenizer.l"
{return(Enum);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 56 "tokenizer.l"
{return(Instanceof);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 57 "tokenizer.l"
{return(Return);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 58 "tokenizer.l"
{return(Transient);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 59 "tokenizer.l"
{return(Catch);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 60 "tokenizer.l"
{return(Extends);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 61 "tokenizer.l"
{return(Int);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 62 "tokenizer.l"
{return(Short);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 63 "tokenizer.l"
{return(Try);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 64 "tokenizer.l"
{return(Char);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 65 "tokenizer.l"
{return(Final);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 66 "tokenizer.l"
{return(Interface);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 67 "tokenizer.l"
{return(Static);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 68 "tokenizer.l"
{return(Void);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 69 "tokenizer.l"
{return(Class);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 70 "tokenizer.l"
{return(Finally);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 71 "tokenizer.l"
{return(Long);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 72 "tokenizer.l"
{return(Strictfp);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 73 "tokenizer.l"
{return(Volatile);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 74 "tokenizer.l"
{return(Const);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 75 "tokenizer.l"
{return(Float);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 76 "tokenizer.l"
{return(Native);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 77 "tokenizer.l"
{return(Super);}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 78 "tokenizer.l"
{return(While);}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 81 "tokenizer.l"
{sscanf(yytext,"%s", yylval.data);
            return (Identifier);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 83 "tokenizer.l"
{}
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 84 "tokenizer.l"
{}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 85 "tokenizer.l"
{sscanf(yytext,"%s", yylval.data);
            return (DecimalIntegerLiteral);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 87 "tokenizer.l"
{sscanf(yytext,"%s", yylval.data);
            return (HexIntegerLiteral);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 89 "tokenizer.l"
{sscanf(yytext,"%s", yylval.data);
            return (OctalIntegerLiteral);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 91 "tokenizer.l"
{sscanf(yytext,"%s", yylval.data);
            return (FloatingPointIntegerLiteral);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 93 "tokenizer.l"
{sscanf(yytext,"%s", yylval.data);
            return (FloatingPointLiteral);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 95 "tokenizer.l"
{sscanf(yytext,"%s", yylval.data);
            return (BooleanIntegerLiteral);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 97 "tokenizer.l"
{sscanf(yytext,"%s", yylval.data);
            return (CharacterLiteral);}
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
#line 99 "tokenizer.l"
{sscanf(yytext,"%s", yylval.data);
            return (TextBlock);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 101 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (EqualTo);
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 105 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (NotOperator);
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 109 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (Tilde);
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 113 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (QuestionMark);
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 117 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (Colon);
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 121 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (RightArrow);
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 125 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (EqualToEqualTo);
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 129 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (GreaterThanEqualTo);
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 133 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (LessThanEqualTo);
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 137 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (NotEqualTo);
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 141 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (AndOperator);
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 145 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (OrOperator);
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 149 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (PlusPlus);
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 153 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (MinusMinus);
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 157 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (Addition);
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 161 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (Substraction);
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 165 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (Product);
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 169 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (Divide);
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 173 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (BitwiseAnd);
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 177 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (BitwiseOr);
}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 181 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (CircumFlex);
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 185 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (Modulo);
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 189 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (LeftShit);
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 193 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (RightShift);
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 197 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (TripleGreaterThan);
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 201 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (AdditionEqualTo);
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 205 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (SubstractionEqualTo);
}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 209 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (ProductEqualTo);
}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 213 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (DivideEqualTo);
}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 217 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (BitWiseAndEqualTo);
}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 221 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (BitWiseOrEqualTo);
}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 225 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (CircumFlexEqualTo);
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 229 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (ModuloEqualTo);
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 233 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (LeftShitEqualTo);
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 237 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (RightShiftEqualTo);
}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 241 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (TripleGreaterThanEqualTo);
}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 245 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (GreaterThan);
    }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 249 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (LessThan);
    }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 254 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (Scope);
    }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 258 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (AtRate);
}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 262 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (LeftSquareBracket);
}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 266 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (RightSquareBracket);
}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 270 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (LeftParanthesis);
}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 276 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (RightParanthesis);
}   
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 282 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
    return (TripleDot);
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 287 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
        return (Dot);
}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 292 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
            return (Comma);
    }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 297 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
        return (LeftCurlyBrace);
}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 302 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
        return (RightCurlyBrace);
}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 307 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
        return (Semicolon);
}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 311 "tokenizer.l"
{
    sscanf(yytext,"%s", yylval.data);
            return (__EMPTY__);
}
	YY_BREAK
case 131:
/* rule 131 can match eol */
YY_RULE_SETUP
#line 316 "tokenizer.l"
{sscanf(yytext,"%s", yylval.data);
            return (StringLiteral);}
	YY_BREAK
case 132:
/* rule 132 can match eol */
YY_RULE_SETUP
#line 318 "tokenizer.l"
{}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 320 "tokenizer.l"
{printf("error! unrecognised input character :%s, skipping\n", yytext);}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 321 "tokenizer.l"
ECHO;
	YY_BREAK
#line 1909 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 480 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 480 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 479);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 321 "tokenizer.l"



int yywrap() {}
